### ISSUE TITLE
License

### ISSUE THREAD

**Issue by wenqiny** [lhao03/lhao03.github.io#12]
Hi Lucy,

The layout and style of your personal web site is pretty good, less is more! I'm planning to build my own personal weblike, I want to fork your code, but it seems you don't assign a license for this repo, is any plan  for it？ Any help would be very appreciated! Thanks!

**Comment by lhao03** [comment]
Hey there! Sorry for not noticing this sooner, I've added a license now. You can now go ahead and fork the code :)
